// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: gauss.proto

package server

import (
	"context"

	"GaussConsul/service/gauss/rpc/internal/logic"
	"GaussConsul/service/gauss/rpc/internal/svc"
	"GaussConsul/service/gauss/rpc/types/gauss"
)

type GaussServer struct {
	svcCtx *svc.ServiceContext
	gauss.UnimplementedGaussServer
}

func NewGaussServer(svcCtx *svc.ServiceContext) *GaussServer {
	return &GaussServer{
		svcCtx: svcCtx,
	}
}

func (s *GaussServer) HealthCheck(ctx context.Context, in *gauss.HealthCheckRequest) (*gauss.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}
