// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DeleteUserRequest struct {
	Id int64 `json:"id"`
}

type DeleteUserResponse struct {
	Status bool `json:"status"`
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   string `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
	Mobile string `json:"mobile"`
}

type UpdateUserRequest struct {
	Name     string `json:"name,optional"`
	Mobile   string `json:"mobile,optional"`
	Gender   string `json:"gender,optional"`
	PassWord string `json:"passWord,optional"`
}

type UpdateUserResponse struct {
	Status bool `json:"status"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
	Mobile string `json:"mobile"`
}
